import type { Article, Project } from '@while-building/types';

// Sample CMS content (including drafts and archived items) until while-building-api has content
// endpoints. Only `source.ts` reads this file.

export const mockArticles: Article[] = [
  {
    id: 'article-1',
    slug: 'running-postgresql-on-a-kubernetes-homelab',
    title: 'Running PostgreSQL on a Kubernetes Homelab',
    description: 'What I learned while running PostgreSQL on a small Kubernetes homelab.',
    category: 'DevOps',
    status: 'PUBLISHED',
    publishedAt: '2026-09-12',
    readingTimeMinutes: 9,
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-12T08:30:00Z',
  },
  {
    id: 'article-2',
    slug: 'building-a-nestjs-api-from-scratch',
    title: 'Building a NestJS API from Scratch',
    description: 'Notes and lessons from building a backend with NestJS.',
    category: 'Backend',
    status: 'PUBLISHED',
    publishedAt: '2026-08-27',
    readingTimeMinutes: 12,
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-27T07:45:00Z',
  },
  {
    id: 'article-3',
    slug: 'what-i-learned-running-my-first-k3s-cluster',
    title: 'What I Learned Running My First k3s Cluster',
    description: 'Things I learned while experimenting with k3s on a Mini PC.',
    category: 'Kubernetes',
    status: 'PUBLISHED',
    publishedAt: '2026-08-09',
    readingTimeMinutes: 7,
    createdAt: '2026-08-01T15:20:00Z',
    updatedAt: '2026-08-09T06:10:00Z',
  },
  {
    id: 'article-4',
    slug: 'things-i-broke-while-building-my-homelab',
    title: 'Things I Broke While Building My Homelab',
    description: 'A collection of failures, debugging sessions and lessons learned.',
    category: 'Homelab',
    status: 'PUBLISHED',
    publishedAt: '2026-07-21',
    readingTimeMinutes: 10,
    createdAt: '2026-07-10T18:00:00Z',
    updatedAt: '2026-07-21T09:00:00Z',
  },
  {
    id: 'article-5',
    slug: 'splitting-a-frontend-into-a-monorepo',
    title: 'Splitting a Frontend into a Monorepo',
    description: 'Moving a single Vite app to pnpm workspaces and Turborepo.',
    category: 'Frontend',
    status: 'DRAFT',
    publishedAt: null,
    readingTimeMinutes: 8,
    createdAt: '2026-09-24T10:00:00Z',
    updatedAt: '2026-09-26T16:40:00Z',
  },
  {
    id: 'article-6',
    slug: 'cookie-based-auth-for-an-spa',
    title: 'Cookie-Based Auth for an SPA',
    description: 'httpOnly refresh cookies, in-memory access tokens and what can go wrong.',
    category: 'Security',
    status: 'DRAFT',
    publishedAt: null,
    readingTimeMinutes: 11,
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-25T11:15:00Z',
  },
  {
    id: 'article-7',
    slug: 'my-first-docker-compose-setup',
    title: 'My First Docker Compose Setup',
    description: 'An early write-up, replaced by the k3s articles.',
    category: 'DevOps',
    status: 'ARCHIVED',
    publishedAt: '2026-05-02',
    readingTimeMinutes: 6,
    createdAt: '2026-04-28T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'project-1',
    slug: 'personal-homelab',
    name: 'Personal Homelab',
    description: 'A small Kubernetes-based homelab running on a Mini PC.',
    technologies: ['k3s', 'Docker', 'Argo CD', 'Cloudflare'],
    stage: 'active',
    featured: true,
    status: 'PUBLISHED',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'project-2',
    slug: 'mcp-analytics-playground',
    name: 'MCP Analytics Playground',
    description: 'An experiment around using MCP to analyze website data.',
    technologies: ['TypeScript', 'NestJS', 'MCP'],
    stage: 'experimental',
    featured: true,
    status: 'PUBLISHED',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-02T10:00:00Z',
  },
  {
    id: 'project-3',
    slug: 'developer-playground',
    name: 'Developer Playground',
    description: 'Small experiments, prototypes and things I build while learning.',
    technologies: ['React', 'Node.js', 'Docker'],
    stage: 'active',
    featured: true,
    status: 'PUBLISHED',
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
  {
    id: 'project-4',
    slug: 'while-building-cms',
    name: 'While Building CMS',
    description: 'The internal tool used to manage this site.',
    technologies: ['React', 'TanStack Query', 'Turborepo'],
    stage: 'experimental',
    featured: false,
    status: 'DRAFT',
    createdAt: '2026-09-24T10:00:00Z',
    updatedAt: '2026-09-26T18:00:00Z',
  },
];
